### ISSUE TITLE
correction to deploy instructions

### ISSUE THREAD

**Issue by c4pt000** [gerwim/pfSense-backup#1]
Clone this git repository (and cd into it)
Run docker build -t pfSenseBackup .
Run (basically) the same command as above: docker run --rm -v /my/backup/folder:/app/backups pfSenseBackup https://192.168.0.1:8443 admin password

should be """""

Clone this git repository (and cd into it)
#lowercase for repository
#invalid argument "pfSenseBackup" for "-t, --tag" flag: invalid reference format: repository name must be #lowercase

should be """""

Run docker build -t pfsensebackup .
Run (basically) the same command as above: docker run --rm -v /my/backup/folder:/app/backups pfSenseBackup https://192.168.0.1:8443 admin password

**Comment by gerwim** [comment]
Thanks @c4pt000. I will look into it tomorrow, along with an improved Dockerfile to decrease the build size.

**Comment by gerwim** [comment]
Fixed in https://github.com/gerwim/pfSense-backup/commit/a02f302f623d4d922aa378265fc0e4e87dacd97e
